#!/usr/bin/env bash

cp ~/android/kernel/982t/out/target/product/mts982t/kernel_mts982t.bin ~/android/kernel/982t/tools/mtk-tools
cp ~/android/kernel/982t/boot/boot.img ~/android/kernel/982t/tools/mtk-tools
cd ~/android/kernel/982t/tools/mtk-tools
./unpack-MT65xx.pl boot.img
rm boot.img
rm boot.img-kernel.img
cd ~/android/kernel/982t/tools/mtk-tools/
./repack-MT65xx.pl -boot kernel_mts982t.bin boot.img-ramdisk boot.img
