#!/usr/bin/env bash

cp /home/kirito9/android/kernel/mts982t/out/target/product/mts982t/kernel_mts982t.bin /home/kirito9/android/tools/mtk-tools
cp /home/kirito9/android/kernel/mts982t/boot/boot.img /home/kirito9/android/tools/mtk-tools
cd /home/kirito9/android/tools/mtk-tools
./unpack-MT65xx.pl boot.img
rm boot.img
rm boot.img-kernel.img
cd /home/kirito9/android/tools/mtk-tools/
./repack-MT65xx.pl -boot kernel_mts982t.bin boot.img-ramdisk boot.img
